version: "2"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
output:
  show-stats: false
  sort-order:
    - file
    - linter
    - severity
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocritic
    - godoclint
    - gosec
    - govet
    - ineffassign
    - makezero
    - modernize
    - nilerr
    - noctx
    - nolintlint
    - paralleltest
    - predeclared
    - reassign
    - staticcheck
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usetesting
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    errorlint:
      errorf: true
      errorf-multi: true
      asserts: true
      comparison: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
